### ISSUE TITLE
Removing all Spawnpoints with despawn timers <1 or 2min

### ISSUE THREAD

**Issue by Jebula999** [Kneckter/SpawnpointClusterTool#10]
Hey hey,

Not sure how else to put in a feature suggestion/query.
But if it gets all data from our database, would it not be beneficial to also remove all spawn points that have a despawn timer of say 1 - 2 minutes?

Not sure what % of spawn points this will account for, but could reduce the redundant points by quite a number.

**Comment by Kneckter** [comment]
Despawn timer is related to the pokemon table and the time of the hour that a pokemon disappears. That does not play a part in planning paths by spawnpoints (at least with this script). There was an RDM update not long ago to record the "last_seen" time that can be used to derive the duration of a spawn, but none are realistically in the 1-2min range; they used to be 15/30/45/60 min and I think are just 30/60 min now. That can be used to estimate what point in the hour a spawn should appear too. Though, this script cannot plan how long a scanner can be at a point before moving to the next. That would have to be handled by the backend like the old RM spawnpoint scanning. Not knowing how long a scanner takes for each jump will make it impossible to implement something like that as the despawn timing is relative to how fast a scanner can get there.

**Comment by Jebula999** [comment]
Oh I see,

I think I was just being silly and jumping to conclusions when I saw "despawn_sec" in my database.
Presumed it meant that's how long it stays around before despawning.

But now as soon as you mentioned the 15/30/45/60 min timers, I remember reading about that a year or two ago -_-

Thank you for clearing that up, makes a bit more logical sense.
