### ISSUE TITLE
Bootstrap Option

### ISSUE THREAD

**Issue by bbdoc** [Kneckter/SpawnpointClusterTool#9]
Could you add an option to create a boostrap route based on a geofence ? This would be useful for initialising a new area in RDM.
Thanks

**Comment by Kneckter** [comment]
That's what the Create Circles settings are for `-cc` and `-ccr`. It will fill a geofence with circles of the size you want. Use it with the Save Query options and it can update a pokemon instance.

**Comment by bbdoc** [comment]
Oh cool. I didn't understand this option was for this purpose. Perfect then.
